sudo: true 
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install: pip install -r requirements.txt
cache: pip
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/flaskapp.py"
  - export FLASK_DEBUG=1

script: nose2 -v