version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PASSWORD: 'password'
          DEBUG: True
          TESTING: True
          SECRET_KEY: 'badkey'
          circle: 1

    working_directory: ~/flaskapp

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: nose2 -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    machine:
      enabled: true
    working_directory: ~/flaskapp

    steps:
      - checkout
      
      - run:
          name: Deploy Dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then  ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "$SSH_COMMMAND"; fi
        