version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          config: 1

    working_directory: ~/flaskapp

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: nose2 -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
        