version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PASSWORD: 'password'
          DEBUG: True
          TESTING: True
          SECRET_KEY: 'badkey'
          circle: 1

    working_directory: ~/flaskapp

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo pip install -r requirements.txt
            echo "$CIRCLE_BRANCH"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: nose2 -v

      - store_artifacts:
          path: test-reports
          destination: test-reports
          